### ISSUE TITLE
Pointer and strip not showing immediately on bar press

### ISSUE THREAD

**Issue by jihyeon-kimy** [Abhinandan-Kushwaha/react-native-gifted-charts#1002]
### Description

https://github.com/user-attachments/assets/893fa3aa-1a1f-4764-94ea-361d97d68d69

I'm experiencing an issue with the BarChart pointer behavior. 
Currently, the pointer and strip are only displayed after pressing and dragging on a bar, 
even though I have configured the chart for immediate pointer activation.

Expected behavior:
- Pointer and strip should appear immediately when pressing a bar
- No dragging should be required to show the pointer

Current behavior:
- User must press and drag to see the pointer and strip
- Simple press does not trigger the pointer display

```
import {Text} from '@gui/text';

import {Dimensions} from 'react-native';
import {BarChart} from 'react-native-gifted-charts';
import {useToken} from '@gluestack-style/react';
import {formatToKrw} from '@/utils/format-to-krw';
import {VStack} from '@gui/vstack';
import {memo} from 'react';
import Loading from './TotalAssetsGraphLoading';
import DataPoint, {CustomDataPointProps} from '../../CustomDataPoint';

export type TotalAssetsGraphBarItem = {
  index: number;
  value: number;
  label: string;
  totalAssets?: number;
  balance?: number;
  date?: string;
  frontColor?: any;
};

export type TotalAssetsGraphLineItem = {
  value: number;
  label: string;
  customDataPoint?: ({...props}: CustomDataPointProps) => JSX.Element;
};

interface TotalAssetsGraphProps {
  isLoading?: boolean;
  barData?: TotalAssetsGraphBarItem[];
  lineData?: TotalAssetsGraphLineItem[];
  maxValue?: number;
}

const SPACING = 6;

export const TotalAssetsGraph = ({
  isLoading,
  barData,
  lineData,
  maxValue,
}: TotalAssetsGraphProps) => {
  const screenWidth = Dimensions.get('window').width;

  const supportPinkColor = useToken('colors', 'support_pink');
  const textDisableColor = useToken('colors', 'text_disable');
  const primaryNormalColor = useToken('colors', 'primary_normal');
  const textAlternativeColor = useToken('colors', 'text_alternative');
  const borderSolidNormalColor = useToken('colors', 'border_solid_normal');
  const borderSolidNeutralColor = useToken('colors', 'border_solid_neutral');

  return (
    <BarChart
      key={isLoading ? 'total-assets-graph-loading' : 'total-assets-graph'}
      width={screenWidth}
      maxValue={maxValue}
      height={178}
      barWidth={(screenWidth - SPACING * 15) / 12}
      spacing={SPACING}
      minHeight={3}
      yAxisExtraHeight={55}
      labelsExtraHeight={0}
      hideYAxisText={true}
      barBorderTopLeftRadius={8}
      barBorderTopRightRadius={8}
      dashWidth={0}
      frontColor={textDisableColor}
      data={barData}
      lineData={lineData}
      yAxisThickness={0}
      yAxisLabelWidth={0}
      initialSpacing={SPACING * 2}
      endSpacing={SPACING * 2}
      adjustToWidth={true}
      xAxisThickness={1}
      xAxisColor={borderSolidNormalColor}
      xAxisLabelTextStyle={{
        color: textAlternativeColor,
        fontSize: 14,
      }}
      showLine
      lineConfig={{
        thickness: 2,
        color: isLoading ? textDisableColor : primaryNormalColor,
      }}
      isAnimated={true}
      disableScroll
      pointerConfig={{
        activatePointersInstantlyOnTouch: true,
        activatePointersOnLongPress: true,
        activatePointersDelay: 0,
        stripBehindBars: false,
        pointerStripHeight: 178,
        pointerStripColor: borderSolidNeutralColor,
        pointerStripWidth: 1,
        hidePointer1: true,
        strokeDashArray: [4],
        pointerLabelWidth: 150,
        autoAdjustPointerLabelPosition: false,
        shiftPointerLabelY: 20,
        shiftPointerLabelX: -65,
        pointerLabelComponent: ([barItems, _]: TotalAssetsGraphBarItem[]) => {
          const isFirst = barItems.index == 0;
          const isLast = barItems.index == 11;
          return (
            <VStack
              key={`total-assets-graph-${barItems.index}`}
              alignItems={
                isFirst ? 'flex-start' : isLast ? 'flex-end' : 'center'
              }
              left={isFirst ? 65 : isLast ? -65 : 0}>
              <Text textStyle="Caption1_M" color="$status_negative">
                {`총 ${formatToKrw(barItems.totalAssets)}`}
              </Text>
              <Text textStyle="Caption1_M" color={supportPinkColor}>
                {formatToKrw(barItems.balance)}
              </Text>
              <Text textStyle="Caption1_R" color="$text_alternative">
                {barItems.date}
              </Text>
            </VStack>
          );
        },
      }}
    />
  );
};

export default Object.assign(memo(TotalAssetsGraph), {
  Loading,
  DataPoint,
});

```

### Steps to reproduce

-

### version of react-native-gifted-charts

1.4.56

### React Native version

0.76.0

### Platforms

iOS

### Workflow

None

**Comment by Abhinandan-Kushwaha** [comment]
Hi @jihyeon-kimy 👋
Currently, `activatePointersInstantlyOnTouch` works only for Line charts and not for Bar charts. I will try to add it to Bar charts soon. Please star the repo if you liked it 😊

**Comment by Abhinandan-Kushwaha** [comment]
Hi @jihyeon-kimy Thanks for reporting this issue. It has been fixed from versions `1.4.57`  onwards. 🎉

Please use the latest version of the library.

**Comment by jihyeon-kimy** [comment]
@Abhinandan-Kushwaha  

Thanks for fixing the issue! 🎉 I’ve updated to version 1.4.57, and now the pointer and strip appear immediately when pressing a bar, which is great.

However, I’ve noticed a new issue: the pointer no longer appears when pressing and dragging. Previously, users could also activate the pointer by dragging, but now that behavior is not working.

Would it be possible to support both interactions—immediate activation on press and activation while dragging?

Thanks again for your help! 🚀

**Comment by Abhinandan-Kushwaha** [comment]
@jihyeon-kimy I tested on Android simulator and the pointer is working for both- immediately as well as after dragging.
Can you share the code with video, or a [snack](https://snack.expo.dev/) ?

**Comment by jihyeon-kimy** [comment]
Hi @Abhinandan-Kushwaha,

Thanks for checking! The code remains the same, but if you compare the initial video I attached with the latest one, you'll notice a difference.

In the first video, when dragging, the pointer and strip appeared continuously as expected. However, in the current version, they no longer appear consecutively while dragging. Now, a maximum of two pointers are visible at a time, and the strip and pointer do not follow the drag movement smoothly as before.

-----

https://github.com/user-attachments/assets/96b02cee-2636-4eb4-901f-aed6afbe666b

```
import {Text} from '@gui/text';

import {Dimensions} from 'react-native';
import {BarChart} from 'react-native-gifted-charts';
import {useToken} from '@gluestack-style/react';
import {formatToKrw} from '@/utils/format-to-krw';
import {VStack} from '@gui/vstack';
import {memo} from 'react';
import Loading from './TotalAssetsGraphLoading';
import DataPoint, {CustomDataPointProps} from '../../CustomDataPoint';

export type TotalAssetsGraphBarItem = {
  index: number;
  value: number;
  label: string;
  totalAssets?: number;
  balance?: number;
  date?: string;
  frontColor?: any;
};

export type TotalAssetsGraphLineItem = {
  value: number;
  label: string;
  customDataPoint?: ({...props}: CustomDataPointProps) => JSX.Element;
};

interface TotalAssetsGraphProps {
  isLoading?: boolean;
  barData?: TotalAssetsGraphBarItem[];
  lineData?: TotalAssetsGraphLineItem[];
  maxValue?: number;
}

const SPACING = 6;

export const TotalAssetsGraph = ({
  isLoading,
  barData,
  lineData,
  maxValue,
}: TotalAssetsGraphProps) => {
  const screenWidth = Dimensions.get('window').width;

  const supportPinkColor = useToken('colors', 'support_pink');
  const textDisableColor = useToken('colors', 'text_disable');
  const primaryNormalColor = useToken('colors', 'primary_normal');
  const textAlternativeColor = useToken('colors', 'text_alternative');
  const borderSolidNormalColor = useToken('colors', 'border_solid_normal');
  const borderSolidNeutralColor = useToken('colors', 'border_solid_neutral');

  // J_MEMO: bar Chart에서 onPress 즉시, 포인터가 노출되지 않음
  return (
    <BarChart
      key={isLoading ? 'total-assets-graph-loading' : 'total-assets-graph'}
      width={screenWidth}
      maxValue={maxValue}
      height={178}
      barWidth={(screenWidth - SPACING * 15) / 12}
      spacing={SPACING}
      minHeight={3}
      yAxisExtraHeight={55}
      labelsExtraHeight={0}
      hideYAxisText={true}
      barBorderTopLeftRadius={8}
      barBorderTopRightRadius={8}
      dashWidth={0}
      frontColor={textDisableColor}
      data={barData}
      lineData={lineData}
      yAxisThickness={0}
      yAxisLabelWidth={0}
      initialSpacing={SPACING * 2}
      endSpacing={SPACING * 2}
      adjustToWidth={true}
      xAxisThickness={1}
      xAxisColor={borderSolidNormalColor}
      xAxisLabelTextStyle={{
        color: textAlternativeColor,
        fontSize: 14,
      }}
      showLine
      lineConfig={{
        thickness: 2,
        color: isLoading ? textDisableColor : primaryNormalColor,
      }}
      isAnimated={true}
      disableScroll
      pointerConfig={{
        activatePointersInstantlyOnTouch: true,
        activatePointersOnLongPress: true,
        activatePointersDelay: 0,
        stripBehindBars: false,
        pointerStripHeight: 178,
        pointerStripColor: borderSolidNeutralColor,
        pointerStripWidth: 1,
        hidePointer1: true,
        strokeDashArray: [4],
        pointerLabelWidth: 150,
        autoAdjustPointerLabelPosition: false,
        shiftPointerLabelY: 20,
        shiftPointerLabelX: -65,
        pointerLabelComponent: ([barItems, _]: TotalAssetsGraphBarItem[]) => {
          const isFirst = barItems.index == 0;
          const isLast = barItems.index == 11;
          return (
            <VStack
              key={`total-assets-graph-${barItems.index}`}
              alignItems={
                isFirst ? 'flex-start' : isLast ? 'flex-end' : 'center'
              }
              left={isFirst ? 65 : isLast ? -65 : 0}>
              <Text textStyle="Caption1_M" color="$status_negative">
                {`총 ${formatToKrw(barItems.totalAssets)}`}
              </Text>
              <Text textStyle="Caption1_M" color={supportPinkColor}>
                {formatToKrw(barItems.balance)}
              </Text>
              <Text textStyle="Caption1_R" color="$text_alternative">
                {barItems.date}
              </Text>
            </VStack>
          );
        },
      }}
    />
  );
};

export default Object.assign(memo(TotalAssetsGraph), {
  Loading,
  DataPoint,
});

```

**Comment by mtseo01** [comment]
Hi @Abhinandan-Kushwaha,

I'm experiencing the same issue as @jihyeon-kimy mentioned in their last comment.

On Android, the pointer drag stops after 1-2 data points while iOS works perfectly fine.

**Environment:**
- react-native-gifted-charts: 1.4.70
- React Native: 0.78.1
- Android: Emulator (sdk_gphone64_arm64)
- iOS: Works fine

This issue still exists in the latest version. Could you please reopen this?
